# Site settings
title: Gabrieldrs' space
description: "A blog for sharing thoughts on anything."
url: "https://gabrieldrs.com"
ogimage: "img/default-ogimage.png"
author:
  name: "Gabriel dos Reis Sezefredo"
  email: "contact@gabrieldrs.com"
  url: "https://gabrieldrs.com"


# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page-:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
reverse: false
